# -*- coding: utf-8 -*-
"""Experiment1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QL40SSninSP4P9SaW3oI50j_4gpWBiS-
"""



a=50
b=50
c=a+b
print(c)