# -*- coding: utf-8 -*-
"""Loadingdataset.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J4c-1m_FNdlr6IoK_9Sp7uwwv0BXShyz
"""

from sklearn import datasets
iris= datasets.load_iris()
digits=datasets.load_digits()
print(digits.data)